export const data = [
  {
    id: 1,
    name: "Apples",
    category: "Fruit",
    src: "/assets/images/apples.jpg",
    season_start: "2023-01-01",
    season_end: "2023-12-31",
    month_start: 1,
    month_end: 12,
    isAvailable: false,
    apiRoute: "apple",
  },
  {
    id: 2,
    name: "Apricots",
    category: "Fruit",
    src: "",
    season_start: "2023-06-15",
    season_end: "2023-08-31",
    month_start: 6,
    month_end: 8,
    isAvailable: false,
    apiRoute: "apricot",
  },
  {
    id: 3,
    name: "Pears",
    category: "Fruit",
    src: "",
    season_start: "2023-08-01",
    season_end: "2023-03-31",
    month_start: 8,
    month_end: 3,
    isAvailable: false,
    apiRoute: "pear",
  },
  {
    id: 4,
    name: "Strawberries",
    category: "Fruit",
    src: "",
    season_start: "2023-05-01",
    season_end: "2023-08-31",
    month_start: 5,
    month_end: 8,
    isAvailable: false,
    apiRoute: "strawberry",
  },
  {
    id: 5,
    name: "Black Berries",
    category: "Fruit",
    src: "",
    season_start: "2023-06-15",
    season_end: "2023-10-15",
    month_start: 6,
    month_end: 10,
    isAvailable: false,
    apiRoute: "blackberry",
  },
  {
    id: 6,
    name: "Blueberries",
    category: "Fruit",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-10-15",
    month_start: 6,
    month_end: 10,
    isAvailable: false,
    apiRoute: "blueberry",
  },
  {
    id: 7,
    name: "Raspberries",
    category: "Fruit",
    src: "",
    season_start: "2023-05-15",
    season_end: "2023-10-31",
    month_start: 5,
    month_end: 10,
    isAvailable: false,
    apiRoute: "raspberry",
  },
  {
    id: 8,
    name: "Red Currants",
    category: "Fruit",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-09-30",
    month_start: 6,
    month_end: 9,
    isAvailable: false,
    apiRoute: "red currant",
  },
  {
    id: 9,
    name: "Black Currants",
    category: "Fruit",
    src: "",
    season_start: "2023-06-15",
    season_end: "2023-08-31",
    month_start: 6,
    month_end: 8,
    isAvailable: false,
    apiRoute: "black currant",
  },
  {
    id: 10,
    name: "Cherries",
    category: "Fruit",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-08-31",
    month_start: 6,
    month_end: 8,
    isAvailable: false,
    apiRoute: "cherry",
  },
  {
    id: 11,
    name: "Mirabelles",
    category: "Fruit",
    src: "",
    season_start: "2023-07-01",
    season_end: "2023-10-31",
    month_start: 7,
    month_end: 10,
    isAvailable: false,
    apiRoute: "mirabelle",
  },
  {
    id: 12,
    name: "Plums",
    category: "Fruit",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-10-31",
    month_start: 6,
    month_end: 10,
    isAvailable: false,
    apiRoute: "plum",
  },
  {
    id: 13,
    name: "Cranberries",
    category: "Fruit",
    src: "",
    season_start: "2023-07-15",
    season_end: "2023-10-31",
    month_start: 7,
    month_end: 10,
    isAvailable: false,
    apiRoute: "cranberry",
  },
  {
    id: 14,
    name: "Quinces",
    category: "Fruit",
    src: "",
    season_start: "2023-10-01",
    season_end: "2023-12-31",
    month_start: 10,
    month_end: 12,
    isAvailable: false,
    apiRoute: "quinces",
  },
  {
    id: 15,
    name: "Gooseberries",
    category: "Fruit",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-08-31",
    month_start: 6,
    month_end: 8,
    isAvailable: false,
    apiRoute: "gooseberry",
  },
  {
    id: 16,
    name: "Grapes",
    category: "Fruit",
    src: "",
    season_start: "2023-08-15",
    season_end: "2023-10-31",
    month_start: 8,
    month_end: 10,
    isAvailable: false,
    apiRoute: "grape",
  },
  {
    id: 17,
    name: "Artichokes",
    category: "Vegetable",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-09-30",
    month_start: 6,
    month_end: 9,
    isAvailable: false,
    apiRoute: "artichoke",
  },
  {
    id: 18,
    name: "Aubergines",
    category: "Vegetable",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-10-31",
    month_start: 6,
    month_end: 10,
    isAvailable: false,
    apiRoute: "eggplant",
  },
  {
    id: 19,
    name: "Cauliflower",
    category: "Vegetable",
    src: "/assets/images/cauliflower.jpg",
    season_start: "2023-04-15",
    season_end: "2023-12-15",
    month_start: 4,
    month_end: 12,
    isAvailable: false,
    apiRoute: "cauliflower",
  },
  {
    id: 20,
    name: "Green Beans",
    category: "Vegetable",
    src: "",
    season_start: "2023-05-15",
    season_end: "2023-10-31",
    month_start: 5,
    month_end: 10,
    isAvailable: false,
    apiRoute: "green bean",
  },
  {
    id: 21,
    name: "Broccoli",
    category: "Vegetable",
    src: "",
    season_start: "2023-05-15",
    season_end: "2023-12-15",
    month_start: 5,
    month_end: 12,
    isAvailable: false,
    apiRoute: "broccoli",
  },
  {
    id: 22,
    name: "Chinese Cabbage",
    category: "Vegetable",
    src: "",
    season_start: "2023-05-01",
    season_end: "2023-03-31",
    month_start: 5,
    month_end: 3,
    isAvailable: false,
    apiRoute: "chinese cabbage",
  },
  {
    id: 23,
    name: "Pak Choi",
    category: "Vegetable",
    src: "",
    season_start: "2023-05-01",
    season_end: "2023-10-31",
    month_start: 5,
    month_end: 10,
    isAvailable: false,
    apiRoute: "pak choi",
  },
  {
    id: 24,
    name: "Peas",
    category: "Vegetable",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-10-31",
    month_start: 6,
    month_end: 10,
    isAvailable: false,
    apiRoute: "peas",
  },
  {
    id: 25,
    name: "Fennel",
    category: "Vegetable",
    src: "",
    season_start: "2023-05-15",
    season_end: "2023-12-31",
    month_start: 5,
    month_end: 12,
    isAvailable: false,
    apiRoute: "fennel",
  },
  {
    id: 26,
    name: "Bell Peppers",
    category: "Vegetable",
    src: "",
    season_start: "2023-7-01",
    season_end: "2023-10-31",
    month_start: 7,
    month_end: 10,
    isAvailable: false,
    apiRoute: "bell pepper",
  },
  {
    id: 27,
    name: "Green Cabbage",
    category: "Vegetable",
    src: "",
    season_start: "2023-10-01",
    season_end: "2023-03-31",
    month_start: 10,
    month_end: 3,
    isAvailable: false,
    apiRoute: "green cabbage",
  },
  {
    id: 28,
    name: "Cucumber",
    category: "Vegetable",
    src: "/assets/images/cucumber.jpg",
    season_start: "2023-03-01",
    season_end: "2023-10-31",
    month_start: 3,
    month_end: 10,
    isAvailable: false,
    apiRoute: "cucumber",
  },
  {
    id: 29,
    name: "Kohlrabi",
    category: "Vegetable",
    src: "/assets/images/kohlrabi.jpg",
    season_start: "2023-04-15",
    season_end: "2023-12-15",
    month_start: 4,
    month_end: 12,
    isAvailable: false,
    apiRoute: "kohlrabi",
  },
  {
    id: 30,
    name: "Pumpkin",
    category: "Vegetable",
    src: "",
    season_start: "2023-07-01",
    season_end: "2023-12-15",
    month_start: 7,
    month_end: 12,
    isAvailable: false,
    apiRoute: "pumpkin",
  },
  {
    id: 31,
    name: "Swiss Chard",
    category: "Vegetable",
    src: "/assets/images/swiss_chard.jpg",
    season_start: "2023-03-01",
    season_end: "2023-11-31",
    month_start: 3,
    month_end: 11,
    isAvailable: false,
    apiRoute: "swiss chard",
  },
  {
    id: 32,
    name: "Carrots",
    category: "Vegetable",
    src: "/assets/images/carrots.jpg",
    season_start: "2023-01-01",
    season_end: "2023-12-31",
    month_start: 1,
    month_end: 12,
    isAvailable: false,
    apiRoute: "carrots",
  },
  {
    id: 33,
    name: "Leeks",
    category: "Vegetable",
    src: "/assets/images/leeks.jpg",
    season_start: "2023-01-01",
    season_end: "2023-12-31",
    month_start: 1,
    month_end: 12,
    isAvailable: false,
    apiRoute: "leek",
  },
  {
    id: 34,
    name: "Red Radish",
    category: "Vegetable",
    src: "/assets/images/redradish.jpg",
    season_start: "2023-03-01",
    season_end: "2023-11-15",
    month_start: 3,
    month_end: 11,
    isAvailable: false,
    apiRoute: "red radish",
  },
  {
    id: 35,
    name: "Radish",
    category: "Vegetable",
    src: "/assets/images/radish.jpg",
    season_start: "2023-01-01",
    season_end: "2023-12-31",
    month_start: 1,
    month_end: 12,
    isAvailable: false,
    apiRoute: "radish",
  },
  {
    id: 36,
    name: "Rhubarb",
    category: "Vegetable",
    src: "/assets/images/rhubarb.jpg",
    season_start: "2023-04-01",
    season_end: "2023-06-30",
    month_start: 4,
    month_end: 6,
    isAvailable: false,
    apiRoute: "rhubarb",
  },
  {
    id: 37,
    name: "Brussels Sprout",
    category: "Vegetable",
    src: "/assets/images/brusselssprout.jpg",
    season_start: "2023-09-01",
    season_end: "2023-03-31",
    month_start: 9,
    month_end: 3,
    isAvailable: false,
    apiRoute: "brussels sprout",
  },
  {
    id: 38,
    name: "Beetroot",
    category: "Vegetable",
    src: "/assets/images/beetroot.jpg",
    season_start: "2023-01-01",
    season_end: "2023-12-31",
    month_start: 1,
    month_end: 12,
    isAvailable: false,
    apiRoute: "beetroot",
  },
  {
    id: 39,
    name: "Red Cabbage",
    category: "Vegetable",
    src: "/assets/images/redradish.jpg",
    season_start: "2023-05-01",
    season_end: "2023-03-31",
    month_start: 5,
    month_end: 3,
    isAvailable: false,
    apiRoute: "red cabbage",
  },
  {
    id: 40,
    name: "Salsify",
    category: "Vegetable",
    src: "",
    season_start: "2023-10-01",
    season_end: "2023-04-30",
    month_start: 10,
    month_end: 4,
    isAvailable: false,
    apiRoute: "salsify",
  },
  {
    id: 41,
    name: "Asparagus",
    category: "Vegetable",
    src: "/assets/images/asparagus.jpg",
    season_start: "2023-04-01",
    season_end: "2023-06-31",
    month_start: 4,
    month_end: 6,
    isAvailable: false,
    apiRoute: "asparagus",
  },
  {
    id: 42,
    name: "Spinach",
    category: "Vegetable",
    src: "/assets/images/spinach.jpg",
    season_start: "2023-03-31",
    season_end: "2023-12-31",
    month_start: 3,
    month_end: 12,
    isAvailable: false,
    apiRoute: "spinach",
  },
  {
    id: 43,
    name: "Pointed Cabbage",
    category: "Vegetable",
    src: "/assets/images/pointedcabbage.jpg",
    season_start: "2023-04-15",
    season_end: "2023-11-30",
    month_start: 4,
    month_end: 11,
    isAvailable: false,
    apiRoute: "pointed cabbage",
  },
  {
    id: 44,
    name: "Celery",
    category: "Vegetable",
    src: "",
    season_start: "2023-05-15",
    season_end: "2023-12-15",
    month_start: 5,
    month_end: 12,
    isAvailable: false,
    apiRoute: "celery",
  },
  {
    id: 45,
    name: "Tomatoes",
    category: "Vegetable",
    src: "/assets/images/tomatoes.jpg",
    season_start: "2023-04-01",
    season_end: "2023-10-31",
    month_start: 4,
    month_end: 10,
    isAvailable: false,
    apiRoute: "tomatoe",
  },
  {
    id: 46,
    name: "Zucchini",
    category: "Vegetable",
    src: "",
    season_start: "2023-05-15",
    season_end: "2023-10-31",
    month_start: 5,
    month_end: 10,
    isAvailable: false,
    apiRoute: "zucchini",
  },
  {
    id: 47,
    name: "Parsnips",
    category: "Vegetable",
    src: "",
    season_start: "2023-11-01",
    season_end: "2023-02-28",
    month_start: 11,
    month_end: 2,
    isAvailable: false,
    apiRoute: "parsnips",
  },
  {
    id: 48,
    name: "Parsley Root",
    category: "Vegetable",
    src: "",
    season_start: "2023-11-01",
    season_end: "2023-02-28",
    month_start: 11,
    month_end: 2,
    isAvailable: false,
    apiRoute: "parsley root",
  },
  {
    id: 49,
    name: "Onions",
    category: "Vegetable",
    src: "/assets/images/onions.jpg",
    season_start: "2023-01-01",
    season_end: "2023-12-31",
    month_start: 1,
    month_end: 12,
    isAvailable: false,
    apiRoute: "onion",
  },
  {
    id: 50,
    name: "Corn",
    category: "Vegetable",
    src: "",
    season_start: "2023-07-01",
    season_end: "2023-12-31",
    month_start: 7,
    month_end: 12,
    isAvailable: false,
    apiRoute: "corn",
  },
  {
    id: 51,
    name: "Savoy Cabbage",
    category: "Vegetable",
    src: "",
    season_start: "2023-06-01",
    season_end: "2023-03-31",
    month_start: 6,
    month_end: 3,
    isAvailable: false,
    apiRoute: "savoy cabbage",
  },
  {
    id: 52,
    name: "Rutabaga",
    category: "Vegetable",
    src: "",
    season_start: "2023-11-01",
    season_end: "2023-02-28",
    month_start: 11,
    month_end: 2,
    isAvailable: false,
    apiRoute: "rutabaga",
  },
];
